config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }, skip: [:registration]

  namespace :settings do
    resources :profiles, only: [:index, :create]
  end

  get '/plugin', to: 'plugin#index', as: 'plugin'
  scope path: '/new', module: :projects, controller: :project, as: 'new' do
    get  '/', to: :new
    post '/', to: :create
  end

  scope controller: :home, path: '/:username' do
    get '/' => :index, as: 'home'
    get '/stars' => :stars, as: 'stars'
    get '/:project_name' => :project, as: 'project'

    scope module: :projects, path: '/:project_name', as: 'project' do
      get '/star', to: 'project#star'
      get '/fork', to: 'project#fork'
      resource :settings, only: [:update, :destroy] do
        get :index, on: :collection
      end

      resource :editor,  only: [:update] do
        get :index, on: :collection
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :current_page_user
  before_action :project_data, only: [:project]

  def index
    @projects = Project.where({user: @current_page_user})
    @stars_count = Star.where({user: @current_page_user}).size
  end

  def stars
    @stars = Star.where({user: @current_page_user})
    @stars_count = @stars.size
  end

  def project
    unless @project.nil?
      respond_to do |format|
        format.html {nil}
        format.css  {render text: @project.style.stylesheet, content_type: "text/css"}
      end
    else
      respond_to do |format|
        format.html {render_404}
        format.css  {render text: nil, content_type: "text/css"}
      end
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :url, :stylesheet)
    end
end

app/helpers/home_helper.rb
module HomeHelper
  def project_css_path(project)
   "#{root_url}#{project.css_file}"
  end

  def star
    "btn-default"
    "btn-success" if @star.exists?
  end
end

app/views/home/_complete_css.html.haml
.panel.colourable
  .panel-heading
    %span.panel-title Complete CSS
  .panel-body
    .code

app/views/home/_option.html.haml
.panel.panel-default
  / Default panel contents
  .panel-heading= t('options')
  -# .panel-body
    -# %p ...
  / List group
  %ul.list-group
    %li.list-group-item
      = link_to project_editor_path do
        %span.octicon.octicon-pencil
        &nbsp;
        = t('helper.edit')
    %li.list-group-item
      = link_to project_settings_path do
        %span.octicon.octicon-tools
        &nbsp;
        = t('settings')

app/views/home/_profile.html.haml
.profile-block.text-center
  .panel.profile-photo
    = image_tag "http://graph.facebook.com/#{@current_page_user.uid}/picture?type=large", alt: @current_page_user.name
  .profile-full-name
    %h3= @current_page_user.name
  -# %a.btn.btn-success{:href => "#"}
  -#   %i.fa.fa-check
  -#   Following
%hr/
.details
  %a{:href => "#"}
    %i.profile-list-icon.fa.fa-envelope{:style => "color: #888"}
    &nbsp;
    = @current_page_user.email
%hr/
.btn-group.btn-group-justified.stats
  %a{:href => stars_path}
    %strong.star_count
      = @stars_count
    %br/
    %span Starred

app/views/home/index.html.haml
.row#home
  .col-md-3
    = render partial: "profile"
  .col-md-9
    .panel.panel-default
      / Default panel contents
      .panel-heading
        = t('projects')
        %ul.nav.nav-tabs.nav-tabs-xs
          %li
            %a{href: stars_path(params[:username])}
              %span.btn-label.icon.octicon.octicon-star
              Stars
      / List group
      %ul.list-group
        - @projects.each do |project|
          %li.list-group-item
            = link_to(project.name, project_path(@current_page_user.username, project.name))

app/views/home/project.html.haml
.row#project
  .col-md-12.css_link
    .input-group
      %span.input-group-addon CSS
      %input.form-control#css_link{placeholder: "CSS", type: "text", value: project_css_path(@project)}
  .row
    .col-md-12
      .hide
        = text_area_tag :stylesheet, @project.style.stylesheet, id: 'css_code'
      - if current_user_access?
        .col-md-10
          = render partial: 'complete_css'
        .col-md-2
          = render partial: 'option'
      - else
        .col-md-12
          = render partial: 'complete_css'

app/views/home/settings.html.haml
.row#project_settings
  .col-md-3
    .panel.panel-default
      / Default panel contents
      .panel-heading
        %h3.panel-title= t('options')
      -# .panel-body
      / List group
      %ul.list-group
        %li.list-group-item
          =link_to t('profile'), settings_profiles_path
  .col-md-9
    - if @project.errors.any?
      .alert.alert-danger{:role => "alert"}
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        - @project.errors.each do |attr, message|
          = message
    .panel.panel-default
      / Default panel contents
      .panel-heading
        %h3.panel-title= t('settings')
      .panel-body
        = form_for @project, url: '', method: :post do |f|
          %dl
            %dt= t('profiles.name')
            %dd= f.text_field :name, class: 'form-control', placeholder: t('project.name')
            %dt= t('profiles.url')
            %dd= f.email_field :url, class: 'form-control', placeholder: t('project.url')
          %p
            = f.submit t('helper.update'), class: 'btn btn-success'
    -# danger
    - if @project.errors.any?
      .alert.alert-danger{:role => "alert"}
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        - @project.errors.each do |attr, message|
          = message
    .panel.panel-danger
      / Default panel contents
      .panel-heading
        %h3.panel-title= t('helper.danger')
      .panel-body
        = form_for @project, url: '', method: :post do |f|
          %h4.pull-left
            = t('project.del_description')
          %p.pull-right
            = f.submit t('helper.delete'), class: 'btn btn-danger'

app/views/home/stars.html.haml
.row#home
  .col-md-3
    = render partial: "profile"
  .col-md-9
    .panel.panel-default
      / Default panel contents
      .panel-heading
        = t('stars')
        %ul.nav.nav-tabs.nav-tabs-xs
          %li
            %a{href: home_path(params[:username])}
              Projects
      / List group
      %ul.list-group
        - @stars.each do |star|
          %li.list-group-item
            = link_to(star.project.name, project_path(star.project.user.username, star.project.name))