config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }, skip: [:registration]

  namespace :settings do
    resources :profiles, only: [:index, :create]
  end

  get '/plugin', to: 'plugin#index', as: 'plugin'
  scope path: '/new', module: :projects, controller: :project, as: 'new' do
    get  '/', to: :new
    post '/', to: :create
  end

  scope controller: :home, path: '/:username' do
    get '/' => :index, as: 'home'
    get '/stars' => :stars, as: 'stars'
    get '/:project_name' => :project, as: 'project'

    scope module: :projects, path: '/:project_name', as: 'project' do
      get '/star', to: 'project#star'
      get '/fork', to: 'project#fork'
      resource :settings, only: [:update, :destroy] do
        get :index, on: :collection
      end

      resource :editor,  only: [:update] do
        get :index, on: :collection
      end
    end
  end

end

app/views/common/_errors_nav.html.haml
.header
  %a.logo{:href => root_path}
    = image_tag("icon/icon_32.png", alt: "Redesign",  class: "menu_icon", style: "margin-top: -4px;")
    \&nbsp;
    %strong Redesign
  / / .logo
/ / .header

app/views/common/_footer.html.haml
%section.footer
  .container
    .pull-left
      © 2014 Redesign

    .pull-right
      jiunjiun /
      quietmes@gmail.com

    %span.logo
      = image_tag("icon/icon_b_32.png", alt: "Redesign", class: "logo")

app/views/common/_nav.html.haml
#main-navbar.navbar.navbar-inverse{:role => "navigation"}
  .navbar-inner
    / Main navbar header
    .navbar-header
      / Logo
      %a.navbar-brand{:href => root_path}
        = image_tag("icon/icon_32.png", alt: "Redesign", size: "24x24", class: "menu_icon")
        Redesign
      / Main navbar toggle
      %button.navbar-toggle.collapsed{"data-target" => "#main-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %i.navbar-icon.fa.fa-bars
    / / .navbar-header
    #main-navbar-collapse.collapse.navbar-collapse.main-navbar-collapse
      / / .navbar-nav
      .right.clearfix
        %ul.nav.navbar-nav.pull-right.right-navbar-nav
          - if user_signed_in?
            %li
              = link_to home_path(current_user.username), class: "user-menu"  do
                = image_tag "http://graph.facebook.com/v2.2/#{current_user.uid}/picture?type=normal", size: "24x24", alt: current_user.name
                %span
                  %strong= current_user.name
              %li
                = link_to new_path, data: {toggle: "tooltip", placement: "bottom", "original-title"=> t('helper.add')} do
                  %i.octicon.octicon-plus
              %li
                = link_to settings_profiles_path, data: {toggle: "tooltip", placement: "bottom", "original-title"=> t('settings')} do
                  %i.octicon.octicon-gear
              %li
                = link_to destroy_user_session_path, :method => :delete, data: {toggle: "tooltip", placement: "bottom", "original-title"=> t('sign_out')} do
                  %i.octicon.octicon-sign-out
          - else
            %li
              = button_to user_omniauth_authorize_path(:facebook), class: 'btn btn-primary btn-flat navbar-btn' do
                %i.fa.fa-facebook
                = t('sign_in')
          / / .navbar-nav
        / / .right
    / / #main-navbar-collapse
  / / .navbar-inner

app/views/common/_project_nav.html.haml
#project-nav
  .page-header
    .row
      / Page header, center on small screens
      %h3.col-xs-12.col-sm-6.text-left-sm
        %i.fa.fa-css3.page-header-icon
        \&nbsp;
        = link_to @current_page_user.username, home_path(@current_page_user.username)
        \/
        = link_to @project.name, project_path(@current_page_user.username, @project.name)
        %small
          \-
          = link_to @project.url, @project.url
        - if @project.from_project
          .fork-details
            %small
              forked from
              = link_to "#{@project.from_project.user.username} / #{@project.from_project.name}", project_path(@project.from_project.user.username, @project.from_project.name)
      .col-xs-12.col-sm-6.text-right
        = button_to project_star_path, method: :get, remote: true, id: "star", class: "btn btn-flat btn-labeled #{star}" do
          %span.btn-label.icon.octicon.octicon-star
            &nbsp;
            Star
          %span#star_count
            = @star_project_count
        &nbsp;&nbsp;&nbsp;&nbsp;
        = link_to project_fork_path, class: "btn btn-flat btn-labeled btn-default" do
          %span.btn-label.icon.octicon.octicon-repo-forked
            &nbsp;
            Fork
          %span#fork_count
            = @fork_count